bitbake-worker: Fix bitbake -n
Without this you see:

File "bitbake/bin/bitbake-worker", line 201, in fork_off_task
    os._exit(child())
TypeError: an integer is required

Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>