fetch2/git: Fix trailing slash in clone command causing double slash in alternates
The unpack() method constructs the git clone command with a trailing
slash appended to ud.clonedir:

  git clone -s <clonedir>/ <destdir>

When git processes 'clone -s', it writes the source object path into
<destdir>/.git/objects/info/alternates by appending '/objects' to the
source path. The extra trailing slash produces a double slash:

  <clonedir>//objects

Newer versions of git refuse to normalize this path and report:

 error: unable to normalize alternate object path: <path>//objects
  fatal: bad object HEAD

Remove the spurious trailing slash so the alternates file contains a
valid, normalizable path.

Signed-off-by: Jamin Lin <jamin_lin@aspeedtech.com>
Signed-off-by: Mathieu Dubois-Briand <mathieu.dubois-briand@bootlin.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>