lib/bb/tests/fetch.py: add test case to ensure no FetchData attribute error
When using git:// -> file:// in PREMIRRORS and we have the same url
in SRC_URI twice, we reveal the following error:

  AttributeError: 'FetchData' object has no attribute 'shallow'

Add a test case to ensure future changes don't introduce the error
back.

Signed-off-by: Chen Qi <Qi.Chen@windriver.com>
Signed-off-by: Mathieu Dubois-Briand <mathieu.dubois-briand@bootlin.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>