bitbake-setup: remove logging stream configuration
Right now if we leave this and use the existing logger (redefined below
with bb.msg.logger_create), we get all of the outputs twice. Example
with an existing print call converted to logger.error():

  $ bitbake-setup status --setup-dir whatever
  ERROR: Not a valid setup directory: build/init-build-env does not exist in whatever
  ERROR:bitbake-setup:Not a valid setup directory: build/init-build-env does not exist in whatever

Remove the call to logging.basicConfig to avoid this.

Signed-off-by: Antonin Godard <antonin.godard@bootlin.com>
Signed-off-by: Mathieu Dubois-Briand <mathieu.dubois-briand@bootlin.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>