runqueue: fix init of RunQueueScheduler.prio_map; add test for 'basic' scheduler
Before this patch, RunQueueScheduler.prio_map was incorrectly
initialized as a list with a single element, the dictionary keys view.

It broke like so:

ERROR: An uncaught exception occurred in runqueue
Traceback (most recent call last):
  File "/home/laplante/repos/bitbake/lib/bb/runqueue.py", line 1663, in execute_runqueue
    return self._execute_runqueue()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/laplante/repos/bitbake/lib/bb/runqueue.py", line 1629, in _execute_runqueue
    retval = self.rqexe.execute()
             ^^^^^^^^^^^^^^^^^^^^
  File "/home/laplante/repos/bitbake/lib/bb/runqueue.py", line 2357, in execute
    task = self.sched.next()
           ^^^^^^^^^^^^^^^^^
  File "/home/laplante/repos/bitbake/lib/bb/runqueue.py", line 308, in next
    return self.next_buildable_task()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/laplante/repos/bitbake/lib/bb/runqueue.py", line 285, in next_buildable_task
    self.rev_prio_map[tid] = self.prio_map.index(tid)
                             ^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: '/home/laplante/repos/bitbake/lib/bb/tests/runqueue-tests/recipes/a1.bb:do_fetch' is not in list

The other schedulers don't have this problem because they overwrite
prio_map.

AI-Generated: GPT-5.6 Sol

Signed-off-by: Chris Laplante <chris.laplante@agilent.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>