data_smart.py: Skip old override syntax checking for anonymous functions
Fixed when oe-core's path contians append/prepend/remove, e.g.:

/path/to/append_test/oe-core/

Initial a build in any build dirs:
$ bitbake -p
ERROR: Variable __anon_32__buildarea2_xhou_builds_append_test_layers_oe_core_meta_classes_patch_bbclass
contains an operation using the old override syntax. Please convert this
layer/metadata before attempting to use with a newer bitbake.

The anonymous fuctions has no names, so skip checking for it to fix the issue.

Signed-off-by: Robert Yang <liezhi.yang@windriver.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>
(cherry picked from commit ebd00330c41c75797529ff38d6a0955b93f05d1b)
Signed-off-by: Anuj Mittal <anuj.mittal@intel.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>