contrib/hashserv/Dockerfile: Add libgcc to image for runtime dependency
Libgcc is required as a runtime dependency. Without it, we get the
following error:

OSError: Error loading shared library libgcc_s.so.1: No such file or
directory

Signed-off-by: Jesse Riemens <riemensjesse@gmail.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>