fetch2: Ensure UntrustedUrl.msg is str
After e74cfd03afe5aff1f81cbff8c6efcef77c9af618 and related commits were
merged, fetchers call bb.fetch2.check_network_access() with a command,
which is no longer a string, but a list. In case of untrusted URL this
would now cause an exception:
    Exception: TypeError: __str__ returned non-string (type list)

Signed-off-by: Michal Sieron <michalwsieron@gmail.com>
Signed-off-by: Mathieu Dubois-Briand <mathieu.dubois-briand@bootlin.com>