knotty: Fix row/column function return value issue
When the row handling was introduced, one of the callbacks was
missed resulting in:

TypeError: can only concatenate tuple (not "int") to tuple

Fix it.

Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>