fetch2: make unpack_tracer available when fetching mirror URLs
When building the FetchData for fetching from mirrors, pass any
available unpack_tracer to the newly-created object.

This is required to allow fetching repositories that use git-lfs from
MIRRORS or PREMIRRORs and fixes the following failure in the git
fetcher's unpack() method:

AttributeError: 'FetchData' object has no attribute 'unpack_tracer'

[YOCTO #15948].

Signed-off-by: Andreas Mützel <andreas.muetzel@emlix.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>