bitbake.conf: add missing CACHE setting
Without it bitbake fails with

  ERROR: Please ensure CACHE is set to the cache directory for BitBake to use

Signed-off-by: Vasyl Vavrychuk <vvavrychuk@gmail.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>