bin/bitbake-setup: print a note about fetcher log if something fails there
Fetcher errors can sometimes be not particularly helpful, e.g.

ERROR: Fetcher failure for URL: '<url>'. Unable to fetch URL from any source.

In such situations, fetcher log can contain the actual information about what
went wrong, but bitbake-setup would not say where it is (unlike bitbake proper
which does).

So if a log exists, and isn't empty, print a note to try to help users:

ERROR: Check /home/alex/bitbake-builds/poky-master-poky-distro_poky-machine_qemux86-64/layers/logs/fetch_log.20260907192613 for additional information to diagnoze the issue.
ERROR: Fetcher failure for URL: '<url>'. Unable to fetch URL from any source.

Signed-off-by: Alexander Kanavin <alex@linutronix.de>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>